name: My Website
on:
  workflow_dispatch:
    inputs:
      deploy: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install and run Docpress
      uses: this-is-tobi/docpress-action@v0
      with:
        deploy: true
