name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'docpress.json'
      - 'package.json'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build documentation
      run: make docs

    - name: Check build output and create index.html if needed
      run: |
        echo "Contents of _docpress directory:"
        find _docpress -type f | head -20
        echo "Looking for HTML files:"
        find . -name "*.html" -not -path "./node_modules/*" | head -10
        
        # If no index.html exists, create a simple one that loads the SPA
        if [ ! -f "_docpress/index.html" ]; then
          echo "Creating index.html for SPA-style DocPress deployment..."
          cat > _docpress/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Moribito Documentation</title>
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="assets/style.css">
        </head>
        <body>
          <div id="app"></div>
          <script src="assets/script.js"></script>
        </body>
        </html>
        EOF
        fi
        
        echo "Final _docpress contents:"
        find _docpress -type f | sort

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_docpress'

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4